# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: Veracode Static Analysis Pipeline Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  # This workflow contains a job to build and submit pipeline scan, you will need to customize the build process accordingly and make sure the artifact you build is used as the file input to the pipeline scan file parameter
  build-and-upload-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it and copies all sources into ZIP file for submitting for analysis. Replace this section with your applications build steps
    
    - uses: actions/checkout@v4
      with:
        repository: ''
    - run: cd app && mvn clean package

    # You may pin to the exact commit or the version.
    # uses: veracode/veracode-uploadandscan-action@98e2a2941b985e55bfe469ebcb970b2e686625e4
    
    - uses: veracode/veracode-uploadandscan-action@0.2.6
      with:
    # appname
        appname: github test
    # createprofile
        createprofile: false
    # filepath
        filepath: ./app/target/verademo.war
    # version
        version: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
    # vid
        vid: ${{secrets.VERACODE_API_ID}}
    # vkey
        vkey: ${{secrets.VERACODE_API_KEY}}
    # scan timeout
        scantimeout: 300
          
